import { Injectable } from '@angular/core';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { environment } from 'src/environment/environment';
import { Observable, throwError } from 'rxjs';
import { map, catchError,  } from 'rxjs/operators';
import { v4 as uuidv4 } from 'uuid';


import { User } from '../interfaces/interface-user';
import { Articles } from '../interfaces/interface-articles';
@Injectable({
  providedIn: 'root'
})
export class RequestService {

  public autoGeneratedId = uuidv4();
  public action : string = "";
  public id : any;
  private url = environment.baseUrl;


  constructor(private http: HttpClient) { }

  // METHOD : GET
	// DETAILS : Get All Records
  getRequest(){

   let url = this.url + this.action;
   return this.http.get<Articles | User>(url);

  }

  postRequest(formData: Articles){
    formData.id =  this.autoGeneratedId
    console.log(formData, JSON.stringify(formData)
    )
    let url = this.url + this.action;
    return this.http.post<Articles>(url, JSON.stringify(formData), this.httpOptions)
    .pipe(
      map(res=> console.log(res)),
      catchError((error) => {
        console.error(error);
        return throwError('An error occurred while posting the data.');
      })
    );
  }


  protected httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    })
  }
}
